Replace the dot-based transition graph with webview cytoscape
auxoncorp/speqtr-support pull request #20
Opened 2024-02-05 18:50 UTC by jonlamb-gh

2024-02-05 18:57 UTC, mullr commented on vscode/package.json
> +        "postinstall": "npm run updateDependencies",
This seems strange. Does this run on the user's system? What if they don't have npm?

2024-02-05 18:59 UTC, mullr commented on vscode/package.json
> +        "updateDependencies": "node scripts/updateDependencies.js",
Can we call this "copyResources" or something? This made me think it would be mucking with package.lock or something, but it's actually far more benign.

2024-02-05 19:04 UTC, mullr commented on vscode/resources/transitionGraph.js
> +// Copied from https://github.com/CoderAllan/vscode-dgmlviewer
The source is MIT-licensed, and we're Apache-licensed, so we need to deal with that.

2024-02-05 19:08 UTC, mullr commented on vscode/resources/transitionGraph.js
> +                    color: style.getPropertyValue("--vscode-foreground"), // label color
Did you try `color: "var(--vscode-foreground)"`?

2024-02-05 19:17 UTC, mullr commented on vscode/src/transitionGraph.ts
> +    public id: string | undefined = undefined;
The idiomatic way to do this is (I think) `public id?: string;

2024-02-05 19:18 UTC, mullr commented on vscode/src/transitionGraph.ts
> +        if (label !== "" && label !== undefined) {
need to check for undefined first, or the first comparison will error

2024-02-05 19:18 UTC, mullr commented on vscode/src/transitionGraph.ts
> +        if (label !== "" && label !== undefined) {
Should probably be doing the before the `replace` on the previous line, as well.

2024-02-05 19:20 UTC, mullr requested changes
License for that metrics code is the biggie; mostly small style notes otherwise.

2024-02-06 00:14 UTC, jonlamb-gh commented on vscode/resources/transitionGraph.js
> +// Copied from https://github.com/CoderAllan/vscode-dgmlviewer
Added a third-party licenses dir, and in-source attribution. I think that's all we need since they're both permissive.

2024-02-08 17:12 UTC, mullr approved these changes

2024-02-09 11:08 UTC, merged